name: 打包vuepress项目

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 安装依赖和打包项目
      run: |
        npm run build

    - name: 部署
      uses: jamesIves/github-pages-deploy-action@v4
      with: 
        branch: gh-pages
        folder: docs/.vuepress/dist
